### ISSUE TITLE
JavaScript errors are swallowed

### ISSUE THREAD

**Issue by communityportal** [gejgalis/izi-js#1]
all JavaScript errors are swallowed by specified code:

    org.izi.binding.impl.writeByFunction = function () {

    function matcher(object, property) {
        return org.izi.utils.typeOf(object) === 'Function';
    }

    function writer(fn, scope, value) {
        try {
            fn.call(scope, value);
        } catch (e) {      <----------------------------- HERE
        }
    }

    return org.izi.binding.impl.createWriter(matcher, writer);
    }();

Sample stack trace:

    Class.define._showEventsTooltip (EventsPopupView.js:76)
    Base.callParent.callerFn (common-class-model.js:654)
    writer (izi-js.js:5032)
    org.izi.binding.Binding.Binding.transferValue (izi-js.js:4729)
    (anonymous function) (izi-js.js:380)
    (anonymous function) (izi-js.js:592)
    byForEach (izi-js.js:150)
    org.izi.model.Observable.Observable.dispatchEvent (izi-js.js:591)
    org.izi.model.Model.Model.dispatchChange (izi-js.js:766)
    org.izi.model.Model.Model.set (izi-js.js:749)
    org.izi.model.Model.Class.(anonymous function) (izi-js.js:669)
    Class.define.result (HandleClickOnDay.js:14)
    bound (lodash.compat.js:1005)
    _.bind.$.ajax.success (AjaxService.js:112)
    jQuery.Callbacks.fire (jquery.js:3119)
    jQuery.Callbacks.self.fireWith (jquery.js:3231)
    done (jquery.js:9275)
    jQuery.ajaxTransport.send.callback (jquery.js:9685)

The actual function is called because of binding:

        izi.bind().valueOf(this.model, "events").to(this._showEventsTooltip);

So any mistake in our function is swallowed (even calling not defined functions etc.)

**Comment by gejgalis** [comment]
Closed with https://github.com/gejgalis/izi-js/commit/6b635cdc7b08dff6fed28b76d9870928ef7aed51
1.6.1 release is planned for next week.

**Comment by gejgalis** [comment]
izi-js-1.6.1 released. Please let me know if everything is working correctly.

**Comment by communityportal** [comment]
Thanks, we will notify UI team (that provides izi-js for us as dependency in UI stack), about the fix and wait for release with updated dependencies.
